Port 22
Port 443

LogLevel VERBOSE

AllowTcpForwarding yes
GatewayPorts yes

ClientAliveInterval 30
ClientAliveCountMax 3

MaxStartups 100:30:200
MaxSessions 100

Match User tunnel
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    PubkeyAuthentication yes
    AllowTcpForwarding remote
    GatewayPorts yes
    PermitTTY no
    X11Forwarding no
    AllowAgentForwarding no
